# fly.toml app configuration file generated for stadium-back-end on 2023-12-19T17:11:44-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "stadium-back-end"
primary_region = "ewr"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[env]
  PORT = "8080"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
